export const products = [
  { id: 1, name: "Samsung 4K LED TV", price: "45,999", category: "Electronics", inStock: true, image: "assets/samsung-tv.jpg" },
  { id: 2, name: "iPhone 15 Pro", price: "1,29,900", category: "Electronics", inStock: true, image: "assets/iphone-15-pro.jpg" },
  { id: 3, name: "Voltas 1.5 Ton AC", price: "32,490", category: "Electronics", inStock: true, image: "assets/ac-voltas.jpg" },
  { id: 4, name: "MacBook Air M2", price: "94,900", category: "Electronics", inStock: false, image: "assets/macbook-m2.jpg" },
  { id: 5, name: "OnePlus 12R", price: "39,999", category: "Electronics", inStock: true, image: "assets/oneplus-12r.jpg" },
  { id: 6, name: "Sony Bravia 55\"", price: "62,000", category: "Electronics", inStock: true, image: "assets/sony-bravia.jpg" },
  { id: 7, name: "HP Pavilion Laptop", price: "58,500", category: "Electronics", inStock: true, image: "assets/hp-pavilion.jpg" },
  { id: 8, name: "LG Convertible AC", price: "38,990", category: "Electronics", inStock: true, image: "assets/ac-lg.jpg" },
  { id: 9, name: "Google Pixel 8", price: "75,999", category: "Electronics", inStock: false, image: "assets/pixel-8.jpg" },
  { id: 10, name: "Dell Vostro Laptop", price: "42,000", category: "Electronics", inStock: true, image: "assets/dell-vostro.jpg" },

  { id: 11, name: "boAt Airdopes 141", price: "1,299", category: "Accessories", inStock: true, image: "assets/boat-airdopes.jpg" },
  { id: 12, name: "JBL Flip Speaker", price: "8,999", category: "Accessories", inStock: true, image: "assets/jbl-speaker.jpg" },
  { id: 13, name: "Logitech G304 Mouse", price: "2,495", category: "Accessories", inStock: true, image: "assets/logitech-mouse.jpg" },
  { id: 14, name: "Mechanical Keyboard", price: "3,200", category: "Accessories", inStock: true, image: "assets/keyboard-mech.jpg" },
  { id: 15, name: "Sony WH-CH720N", price: "9,990", category: "Accessories", inStock: true, image: "assets/sony-headphones.jpg" },
  { id: 16, name: "Zebronics Soundbar", price: "5,499", category: "Accessories", inStock: false, image: "assets/zebronics-soundbar.jpg" },
  { id: 17, name: "Razer DeathAdder", price: "1,800", category: "Accessories", inStock: true, image: "assets/razer-mouse.jpg" },
  { id: 18, name: "Apple AirPods Gen 3", price: "18,500", category: "Accessories", inStock: true, image: "assets/apple-airpods.jpg" },
  { id: 19, name: "Keychron K2 V2", price: "7,500", category: "Accessories", inStock: true, image: "assets/keychron-k2.jpg" },
  { id: 20, name: "Portronics Speaker", price: "999", category: "Accessories", inStock: true, image: "assets/portronics-speaker.jpg" },

  { id: 21, name: "Executive Office Chair", price: "7,500", category: "Furniture", inStock: true, image: "assets/office-chair.jpg" },
  { id: 22, name: "King Size Wooden Cot", price: "22,000", category: "Furniture", inStock: true, image: "assets/wooden-cot.jpg" },
  { id: 23, name: "Memory Foam Bed", price: "14,999", category: "Furniture", inStock: true, image: "assets/memory-foam-bed.jpg" },
  { id: 24, name: "Glass Study Table", price: "4,200", category: "Furniture", inStock: false, image: "assets/study-table.jpg" },
  { id: 25, name: "Ergonomic Gaming Chair", price: "12,500", category: "Furniture", inStock: true, image: "assets/gaming-chair.jpg" },
  { id: 26, name: "Single Metal Cot", price: "6,800", category: "Furniture", inStock: true, image: "assets/metal-cot.jpg" },
  { id: 27, name: "Orthopedic Mattress", price: "18,000", category: "Furniture", inStock: true, image: "assets/mattress.jpg" },
  { id: 28, name: "Coffee Table Set", price: "3,500", category: "Furniture", inStock: true, image: "assets/coffee-table.jpg" },
  { id: 29, name: "Bean Bag with Beans", price: "1,999", category: "Furniture", inStock: true, image: "assets/bean-bag.jpg" },
  { id: 30, name: "Foldable Wall Table", price: "2,100", category: "Furniture", inStock: true, image: "assets/wall-table.jpg" },
];